// Generated by CoffeeScript 1.3.3
'use strict';

$(function() {
  var hideHandle, hideNav, isDoing, showNav;
  isDoing = 0;
  hideHandle = 0;
  showNav = function() {
    if (isDoing === 0) {
      clearTimeout(hideHandle);
      isDoing = 2;
      $("#nav").stop(true, true).fadeIn(400, function() {
        return isDoing = isDoing - 1;
      });
      $("#bgText").stop(true).fadeOut(400, function() {
        return isDoing = isDoing - 1;
      });
    }
  };
  hideNav = function() {
    $("#nav").stop(true).fadeOut(400);
    $("#bgText").stop(true).fadeIn(400);
  };
  $("#page").mouseenter(showNav).mouseleave(function() {
    clearTimeout(hideHandle);
    return hideHandle = setTimeout(hideNav, 800);
  });
});
